export const fixedTableHeaders =
{
    name: 'Name',
    key: 'companyName',
    sort: true,
}

export const tableHeaders = [
    {
        name: 'Code',
        key: 'code',
        sort: true,

    },
    {
        name: 'Contact Number',
        key: 'contactNo',
        sort: true,
    },
    {
        name: 'Contact Person',
        key: 'contactPerson',
        sort: true,
    },
    {
        name: 'VAT TIN',
        key: 'vatTin',
        sort: true,
    },
    {
        name: 'CST No',
        key: 'cstNo',
        sort: true,
    },
    {
        name: 'PAN',
        key: 'pan',
        sort: true,
    },
    {
        name: 'Email',
        key: 'email',
        sort: true,
    },
    {
        name: 'GSTIN',
        key: 'gstIn',
        sort: true,
    },
    {
        name: 'Address',
        key: 'address',
        sort: true,
    },
    {
        name: 'Terms of Payment',
        key: 'termsOfPayment',
        sort: true,
    },
    {
        name: 'Product Name',
        key: 'productName',
        sort: true,
    },
    {
        name: 'Action',
        key: 'action',
        edit: true
    },
]
export const tableValues = [
    {
        companyName: 'BeyondNXT',
        contactNo:'896858585',
        code: 'NGL001',
        contactPerson:'Ajay G S',
        vat:'1234567FA',
        cst:'20171114',
        gstin:'20171114',
        pan:'BHYPM1927R',
        email: 'test@test.com',
        address: '3201 Temple Ave',
        termsOfPayment:'Online',
        productName:'Rope',
        action:'',
    },
    {
        companyName: 'BeyondNXT',
        contactNo:'896858585',
        code: 'NGL001',
        contactPerson:'Ajay G S',
        vat:'1234567FA',
        cst:'20171114',
        gstin:'20171114',
        pan:'BHYPM1927R',
        email: 'test@test.com',
        address: '3201 Temple Ave',
        termsOfPayment:'Online',
        productName:'Rope',
        action:'',
    },
    {
        companyName: 'BeyondNXT',
        contactNo:'896858585',
        code: 'NGL001',
        contactPerson:'Ajay G S',
        vat:'1234567FA',
        cst:'20171114',
        gstin:'20171114',
        pan:'BHYPM1927R',
        email: 'test@test.com',
        address: '3201 Temple Ave',
        termsOfPayment:'Online',
        productName:'Rope',
        action:'',
    },
    {
        companyName: 'BeyondNXT',
        contactNo:'896858585',
        code: 'NGL001',
        contactPerson:'Ajay G S',
        vat:'1234567FA',
        cst:'20171114',
        gstin:'20171114',
        pan:'BHYPM1927R',
        email: 'test@test.com',
        address: '3201 Temple Ave',
        termsOfPayment:'Online',
        productName:'Rope',
        action:'',
    },
    {
        companyName: 'BeyondNXT',
        contactNo:'896858585',
        code: 'NGL001',
        contactPerson:'Ajay G S',
        vat:'1234567FA',
        cst:'20171114',
        gstin:'20171114',
        pan:'BHYPM1927R',
        email: 'test@test.com',
        address: '3201 Temple Ave',
        termsOfPayment:'Online',
        productName:'Rope',
        action:'',
    },
    {
        companyName: 'BeyondNXT',
        contactNo:'896858585',
        code: 'NGL001',
        contactPerson:'Ajay G S',
        vat:'1234567FA',
        cst:'20171114',
        gstin:'20171114',
        pan:'BHYPM1927R',
        email: 'test@test.com',
        address: '3201 Temple Ave',
        termsOfPayment:'Online',
        productName:'Rope',
        action:'',
    },
    {
        companyName: 'BeyondNXT',
        contactNo:'896858585',
        code: 'NGL001',
        contactPerson:'Ajay G S',
        vat:'1234567FA',
        cst:'20171114',
        gstin:'20171114',
        pan:'BHYPM1927R',
        email: 'test@test.com',
        address: '3201 Temple Ave',
        termsOfPayment:'Online',
        productName:'Rope',
        action:'',
    },
    {
        companyName: 'BeyondNXT',
        contactNo:'896858585',
        code: 'NGL001',
        contactPerson:'Ajay G S',
        vat:'1234567FA',
        cst:'20171114',
        gstin:'20171114',
        pan:'BHYPM1927R',
        email: 'test@test.com',
        address: '3201 Temple Ave',
        termsOfPayment:'Online',
        productName:'Rope',
        action:'',
    },
    {
        companyName: 'BeyondNXT',
        contactNo:'896858585',
        code: 'NGL001',
        contactPerson:'Ajay G S',
        vat:'1234567FA',
        cst:'20171114',
        gstin:'20171114',
        pan:'BHYPM1927R',
        email: 'test@test.com',
        address: '3201 Temple Ave',
        termsOfPayment:'Online',
        productName:'Rope',
        action:'',
    },
    {
        companyName: 'BeyondNXT',
        contactNo:'896858585',
        code: 'NGL001',
        contactPerson:'Ajay G S',
        vat:'1234567FA',
        cst:'20171114',
        gstin:'20171114',
        pan:'BHYPM1927R',
        email: 'test@test.com',
        address: '3201 Temple Ave',
        termsOfPayment:'Online',
        productName:'Rope',
        action:'',
    },
    {
        companyName: 'BeyondNXT',
        contactNo:'896858585',
        code: 'NGL001',
        contactPerson:'Ajay G S',
        vat:'1234567FA',
        cst:'20171114',
        gstin:'20171114',
        pan:'BHYPM1927R',
        email: 'test@test.com',
        address: '3201 Temple Ave',
        termsOfPayment:'Online',
        productName:'Rope',
        action:'',
    },
]